#!/usr/bin/env python3
import os
import random
from datetime import datetime
import argparse
import json

def generate_header():
    """Generate the file header"""
    timestamp = datetime.now().strftime("%a %b %d %H:%M:%S %Y")

    header = f"""# This data file generated by Dynamic DNA (DDNA) Laboratories at: {timestamp}
#
# This file contains raw genetic data, including data that is not used in DDNA reports.
# This data has undergone a general quality review however only a subset of markers have been
# individually reviewed for accuracy. As such, this data is suitable only for research,
# educational, and informational use and not for any medical or diagnostic use.
#
# Below is a text version of your data.  Fields are TAB-separated and
# each line corresponds to a single SNP.  For each SNP, we provide its identifier,
# it chromosomal location realtive to Build 38 of the human reference genome, and the
# genotype call oriented with respect to the plus strand on the human reference sequence.
# More information about Dynamic DNA Laboratories can be found at:
# https://dynamicdnalabs.com
#
# More information on reference human assembly builds:
# https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001405.40/
#
# rsid\tchromosome\tposition\tgenotype\tgs\tbaf\tlrr
"""
    return header

def generate_filename(folder_id=None, month=None, day=None):
    """Generate filename with random elements if not provided"""
    if folder_id is None:
        folder_id = random.randint(100000, 999999)
    if month is None:
        month = random.randint(1, 12)
    if day is None:
        day = random.randint(1, 28)

    return f"{folder_id}_X_X_GSAv3-DTC_GRCh38-{month:02d}-{day:02d}-2025.txt"

def generate_random_metrics():
    """Generate random gs, baf, lrr values"""
    gs = round(random.uniform(0.5, 1.0), 4)
    baf = round(random.uniform(0.0, 1.0), 4)
    lrr = round(random.uniform(-0.5, 0.5), 4)
    return gs, baf, lrr

def load_snps_from_json(json_path, genes=None):
    """
    Load SNP data from JSON file

    Args:
        json_path: Path to JSON file
        genes: List of gene names to include (e.g., ['herc2', 'brca']). None = all

    Returns:
        List of tuples (rsid, chromosome, position, genotype, gs, baf, lrr)
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    snp_data = []
    for gene_name, gene_info in data.items():
        if genes and gene_name not in genes:
            continue

        for variant in gene_info['variants']:
            rsid = variant['rsid']
            chrom = variant['chromosome']
            pos = variant['position']

            # Pick random genotype from available options
            genotype = random.choice(variant['genotypes'])

            # Generate random metrics
            gs, baf, lrr = generate_random_metrics()

            snp_data.append((rsid, chrom, pos, genotype, gs, baf, lrr))

    return snp_data

def generate_genotype_file(output_path, snp_data=None):
    """
    Generate a genotype file

    Args:
        output_path: Full path to output file
        snp_data: List of tuples (rsid, chromosome, position, genotype, gs, baf, lrr)
                  If None, generates sample data
    """
    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        # Write header
        f.write(generate_header())

        # Write SNP data
        if snp_data:
            for snp in snp_data:
                rsid, chrom, pos, genotype, gs, baf, lrr = snp
                f.write(f"{rsid}\t{chrom}\t{pos}\t{genotype}\t{gs}\t{baf}\t{lrr}\n")
        else:
            # Sample data if none provided
            f.write("rs9701055\t1\t630053\tCC\t0.6551\t1\t0.0887\n")

    print(f"Generated: {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate Build 38 genotype files')
    parser.add_argument('--folder', default='.', help='Output folder path')
    parser.add_argument('--folder-id', type=int, help='6-digit folder ID (random if not provided)')
    parser.add_argument('--month', type=int, help='Month (1-12, random if not provided)')
    parser.add_argument('--day', type=int, help='Day (1-28, random if not provided)')
    parser.add_argument('--filename', help='Custom filename (overrides pattern)')
    parser.add_argument('--snp-file', help='Path to SNP data file (TSV format)')
    parser.add_argument('--json-file', help='Path to JSON SNP data file (use with --genes)')
    parser.add_argument('--genes', nargs='+', help='Gene names to include from JSON (e.g., herc2 brca apol1)')

    args = parser.parse_args()

    # Generate filename
    if args.filename:
        filename = args.filename
    else:
        filename = generate_filename(args.folder_id, args.month, args.day)

    output_path = os.path.join(args.folder, filename)

    # Load SNP data if provided
    snp_data = None
    if args.json_file:
        snp_data = load_snps_from_json(args.json_file, args.genes)
    elif args.snp_file:
        snp_data = []
        with open(args.snp_file, 'r') as f:
            for line in f:
                if line.startswith('#'):
                    continue
                parts = line.strip().split('\t')
                if len(parts) == 7:
                    snp_data.append(tuple(parts))

    generate_genotype_file(output_path, snp_data)
